# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addRow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):


    def __init__(self, data):
        self.data = data[0]
        self.colList = map(lambda x : x[0] ,data[1])
        self.colName = []
        self.colText = []
        self.colData = []
        super().__init__()


    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(470, 110)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setContentsMargins(30,30,30,30)

        for num, column in enumerate(self.colList): 
            
            self.colName.append(QtWidgets.QLabel(Dialog))
            self.colName[num].setMaximumSize(QtCore.QSize(16777215, 150))
            self.colName[num].setObjectName(column)
            self.colName[num].setText(column)
            self.gridLayout.addWidget(self.colName[num], 0, num, 1, 1)

            self.colText.append("")
            self.colData.append(QtWidgets.QLineEdit(Dialog))
            font = QtGui.QFont()
            font.setPointSize(10)
            self.colData[num].setFont(font)
            self.colData[num].setPlaceholderText(column)
            self.colData[num].setClearButtonEnabled(True)
            self.colData[num].setObjectName(column)
            self.colData[num].setText(self.colText[num])
            self.gridLayout.addWidget(self.colData[num], 1, num, 1, 1)

        self.addRowbuttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.addRowbuttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.addRowbuttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.addRowbuttonBox.setObjectName("addRowbuttonBox")
        self.gridLayout.addWidget(self.addRowbuttonBox, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMaximumSize(QtCore.QSize(16777215, 150))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.addRowbuttonBox.accepted.connect(lambda : self.uploadData(Dialog))
        self.addRowbuttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "TextLabel"))

    def uploadData(self,Dialog):
        self.data.rowAddData.clear()
        for z in self.colData:
            self.data.rowAddData.append(z.text())
        print(self.data.rowAddData)
        
        msg = self.data.postData(self.data.cursor)
        self.label.setText(str(msg))
        if (msg is not None):
            ...
        else:
            Dialog.accept()
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
