# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dbsetup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from mainViewModel import datamodel

class Ui_dbSetUpDialoge(object):

    def __init__(self, data):
        self.data = data
        super().__init__()


    def setupUi(self, dbSetUpDialoge):
        dbSetUpDialoge.setObjectName("dbSetUpDialoge")
        dbSetUpDialoge.resize(328, 237)
        self.dbSetUpbuttonBox = QtWidgets.QDialogButtonBox(dbSetUpDialoge)
        self.dbSetUpbuttonBox.setGeometry(QtCore.QRect(40, 180, 241, 32))
        self.dbSetUpbuttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.dbSetUpbuttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.dbSetUpbuttonBox.setCenterButtons(True)
        self.dbSetUpbuttonBox.setObjectName("dbSetUpbuttonBox")
        self.widget = QtWidgets.QWidget(dbSetUpDialoge)
        self.widget.setGeometry(QtCore.QRect(60, 30, 221, 134))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.userLineEdit = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.userLineEdit.setFont(font)
        self.userLineEdit.setPlaceholderText("")
        self.userLineEdit.setClearButtonEnabled(True)
        self.userLineEdit.setObjectName("userLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.userLineEdit)
        self.passLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.passLabel.setFont(font)
        self.passLabel.setObjectName("passLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.passLabel)
        self.passLineEdit = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.passLineEdit.setFont(font)
        self.passLineEdit.setClearButtonEnabled(True)
        self.passLineEdit.setObjectName("passLineEdit")
        self.passLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passLineEdit)
        self.hostLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hostLabel.setFont(font)
        self.hostLabel.setObjectName("hostLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.hostLabel)
        self.hostLineEdit = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hostLineEdit.setFont(font)
        self.hostLineEdit.setClearButtonEnabled(True)
        self.hostLineEdit.setObjectName("hostLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.hostLineEdit)
        self.PortLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PortLabel.setFont(font)
        self.PortLabel.setObjectName("PortLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.PortLabel)
        self.portLineEdit = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.portLineEdit.setFont(font)
        self.portLineEdit.setFrame(True)
        self.portLineEdit.setClearButtonEnabled(True)
        self.portLineEdit.setObjectName("portLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.portLineEdit)
        self.nameLabel = QtWidgets.QLabel(self.widget)
        self.nameLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.nameLabel.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)

        self.retranslateUi(dbSetUpDialoge)
        self.dbSetUpbuttonBox.accepted.connect(dbSetUpDialoge.accept)
        self.dbSetUpbuttonBox.rejected.connect(dbSetUpDialoge.reject)
        QtCore.QMetaObject.connectSlotsByName(dbSetUpDialoge)

    def retranslateUi(self, dbSetUpDialoge):
        _translate = QtCore.QCoreApplication.translate
        dbSetUpDialoge.setWindowTitle(_translate("dbSetUpDialoge", "Dialog"))
        self.userLineEdit.setText(_translate("dbSetUpDialoge", self.data.username))
        self.passLabel.setText(_translate("dbSetUpDialoge", "Password"))
        self.passLineEdit.setPlaceholderText(_translate("dbSetUpDialoge", "your pass"))
        self.passLineEdit.setText(_translate("dbSetUpDialoge", self.data.password))
        self.hostLabel.setText(_translate("dbSetUpDialoge", "Host"))
        self.hostLineEdit.setText(_translate("dbSetUpDialoge", self.data.host))
        self.PortLabel.setText(_translate("dbSetUpDialoge", "Port"))
        self.portLineEdit.setText(_translate("dbSetUpDialoge", self.data.port))
        self.nameLabel.setText(_translate("dbSetUpDialoge", "Username"))
    
    def accept(self):
        print("yeeifbwiuef")
        
    def reject(self):
        print("dqwdqwd")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dbSetUpDialoge = QtWidgets.QDialog()
    ui = Ui_dbSetUpDialoge()
    ui.setupUi(dbSetUpDialoge)
    dbSetUpDialoge.show()
    sys.exit(app.exec_())
